version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - /data/postgres:/var/lib/postgresql/data

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - TZ=${TZ}
    ports:
      - 27017:27017

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: keycloak
    #restart: always
    ports:
      - 9999:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: always
    ports:
      - 9411:9411

